services:
  frontend:
    container_name: xllm-nvidia-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=production
      - PORT=3011
    expose:
      - 3011
    depends_on:
      - backend
    networks:
      - xllm-nvidia-network

  backend:
    container_name: xllm-nvidia-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8911:8911"
    expose:
      - 8911
    networks:
      - xllm-nvidia-network

  # pgdatabase:
  #   container_name: xllm-db
  #   image: postgres:16.2-bookworm
  #   ports:
  #     - 5411:5432
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=xllmdb
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=welcome1
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   volumes:
  #     - ./xllmdata:/var/lib/postgresql/data:rw
  #   networks:
  #     - xllm-nvidia-network      

networks:
  xllm-nvidia-network:
    name: xllm-nvidia-network
